version: '3.9'
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - postgres
    ports:
      - "5432:5432"
    volumes:
        - ./postgresql15a_data:/var/lib/postgresql/data
        - ./backups:/mnt/backups
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    restart: always

  odoo14:
    container_name: jenius
    image: jenius:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    networks:
      - postgres
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: nw-cs